eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://172.23.202.112:27017/?directConnection=true
      host: 172.23.202.112
      port: 27017
      database: orderdb
      repositories:
        enabled: true
